import { createExerciseRecord, EXERCISE_TYPE } from "./exercises";

const CATALOG_CREATED_AT = "2026-01-01T00:00:00.000Z";

function catalogExercise(input) {
  return createExerciseRecord({
    ...input,
    createdAt: CATALOG_CREATED_AT,
    updatedAt: CATALOG_CREATED_AT,
  });
}

export const CATALOG_EXERCISES = [
  catalogExercise({
    id: "ex-press-banca-plana",
    name: "Press banca plana con barra olímpica",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 15, max: 15 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-press-inclinado-mancuerna",
    name: "Press inclinado de pecho con mancuerna",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 20, max: 20 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-apertura-pecho",
    name: "Apertura de pecho",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 20, max: 20 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-triceps-poleas",
    name: "Tríceps en poleas",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 30, max: 30 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-fondo-triceps",
    name: "Fondo de tríceps",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 10, max: 10 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-pec-deck",
    name: "Pec deck / contractor de pecho",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 10, max: 12 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-press-hombros-maquina",
    name: "Press de hombros en máquina",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 10, max: 12 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-vuelos-laterales",
    name: "Vuelos laterales con mancuernas",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 12, max: 15 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-triceps-soga",
    name: "Tríceps con soga en polea alta",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 10, max: 12 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-plancha",
    name: "Plancha",
    type: EXERCISE_TYPE.TIMED,
    defaultSets: 2,
    defaultDurationSeconds: 60,
    durationRange: { min: 40, max: 60 },
    restSeconds: 60,
  }),
  catalogExercise({
    id: "ex-jalon-pecho",
    name: "Jalón al pecho con barra",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 10, max: 12 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-remo-triangular",
    name: "Remo con agarre triangular",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 10, max: 12 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-face-pull",
    name: "Face pull con soga",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 10, max: 12 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-curl-tradicional",
    name: "Curl tradicional con mancuernas",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 10, max: 12 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-curl-martillo",
    name: "Curl martillo",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 10, max: 12 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-curl-inverso",
    name: "Curl inverso con barra W",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 10, max: 12 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-prensa-horizontal",
    name: "Prensa horizontal",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 10, max: 12 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-extension-cuadriceps",
    name: "Extensión de cuádriceps",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 10, max: 12 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-curl-femoral",
    name: "Curl femoral acostado",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 10, max: 12 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-pantorrillas",
    name: "Elevaciones de pantorrillas",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 12, max: 15 },
    restSeconds: 90,
  }),
  catalogExercise({
    id: "ex-elevaciones-piernas",
    name: "Elevaciones de piernas",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 10, max: 12 },
    restSeconds: 60,
  }),
  catalogExercise({
    id: "ex-bicicleta-abdominal",
    name: "Bicicleta abdominal",
    type: EXERCISE_TYPE.REPS,
    defaultSets: 3,
    defaultReps: { min: 12, max: 15 },
    restSeconds: 60,
  }),
  catalogExercise({
    id: "ex-cardio-final",
    name: "Cardio final",
    type: EXERCISE_TYPE.TIMED,
    defaultSets: 1,
    defaultDurationSeconds: 1800,
    durationRange: { min: 1800, max: 1800 },
    restSeconds: 0,
  }),
];

export const SEED_EXERCISES = CATALOG_EXERCISES;

export const SEED_ROUTINES = [
  {
    id: "seed-pecho-triceps",
    name: "Pecho + tríceps",
    description: "Pecho y tríceps",
    exercises: [
      { exerciseId: "ex-press-banca-plana", order: 0 },
      { exerciseId: "ex-press-inclinado-mancuerna", order: 1 },
      { exerciseId: "ex-apertura-pecho", order: 2 },
      { exerciseId: "ex-triceps-poleas", order: 3 },
      { exerciseId: "ex-fondo-triceps", order: 4 },
    ],
  },
  {
    id: "seed-espalda-biceps",
    name: "Espalda + bíceps",
    description: "Espalda y bíceps",
    exercises: [
      { exerciseId: "ex-jalon-pecho", order: 0 },
      { exerciseId: "ex-remo-triangular", order: 1 },
      { exerciseId: "ex-face-pull", order: 2 },
      { exerciseId: "ex-curl-tradicional", order: 3 },
      { exerciseId: "ex-curl-martillo", order: 4 },
      { exerciseId: "ex-curl-inverso", order: 5 },
    ],
  },
  {
    id: "seed-piernas-hombros",
    name: "Piernas + hombros",
    description: "Piernas y hombros",
    exercises: [
      { exerciseId: "ex-prensa-horizontal", order: 0 },
      { exerciseId: "ex-extension-cuadriceps", order: 1 },
      { exerciseId: "ex-curl-femoral", order: 2 },
      { exerciseId: "ex-press-hombros-maquina", order: 3 },
      { exerciseId: "ex-vuelos-laterales", order: 4 },
      { exerciseId: "ex-pantorrillas", order: 5 },
    ],
  },
];
